ID = 0
TYPE_INT = 1
TYPE_CHAR = 2
TYPE_DOUBLE = 3
IF = 4
ELSE = 5
WHILE = 6
VOID = 7
RETURN = 8
STRUCT = 9
INT = 10
DOUBLE = 11
CHAR = 12
STRING = 13
COMMA = 14
SEMICOLON = 15
LPAR = 16
RPAR = 17
LBRACKET = 18
RBRACKET = 19
LACC = 20
RACC = 21
END = 22
ADD = 23
SUB = 24
MUL = 25
DIV = 26
DOT = 27
AND = 28
OR = 29
NOT = 30
ASSIGN = 31
EQUAL = 32
NOTEQ = 33
LESS = 34
LESSEQ = 35
GREATER = 36
GREATEREQ = 37

def get_token_name(code):
    token_names = {
        ID: "ID", TYPE_INT: "TYPE_INT", TYPE_CHAR: "TYPE_CHAR", TYPE_DOUBLE: "TYPE_DOUBLE",
        IF: "IF", ELSE: "ELSE", WHILE: "WHILE", VOID: "VOID", RETURN: "RETURN", STRUCT: "STRUCT",
        INT: "INT", DOUBLE: "DOUBLE", CHAR: "CHAR", STRING: "STRING",
        COMMA: "COMMA", SEMICOLON: "SEMICOLON", LPAR: "LPAR", RPAR: "RPAR",
        LBRACKET: "LBRACKET", RBRACKET: "RBRACKET", LACC: "LACC", RACC: "RACC", END: "END",
        ADD: "ADD", SUB: "SUB", MUL: "MUL", DIV: "DIV", DOT: "DOT", AND: "AND", OR: "OR",
        NOT: "NOT", ASSIGN: "ASSIGN", EQUAL: "EQUAL", NOTEQ: "NOTEQ", LESS: "LESS",
        LESSEQ: "LESSEQ", GREATER: "GREATER", GREATEREQ: "GREATEREQ"
    }
    return token_names.get(code, f"UNKNOWN({code})")